export const analyticsSummaryJsonSchema = {
  type: 'object',
  required: [
    'period',
    'startDate',
    'endDate',
    'scheduledCount',
    'completedCount',
    'completionRate',
    'totalTargetCount',
    'totalCompletedCount',
    'progressRate',
  ],
  properties: {
    period: { type: 'string', enum: ['day', 'week', 'month'] },
    startDate: { type: 'string', format: 'date' },
    endDate: { type: 'string', format: 'date' },
    scheduledCount: { type: 'integer', minimum: 0 },
    completedCount: { type: 'integer', minimum: 0 },
    completionRate: { type: 'number', minimum: 0, maximum: 100 },
    totalTargetCount: { type: 'integer', minimum: 0 },
    totalCompletedCount: { type: 'integer', minimum: 0 },
    progressRate: { type: 'number', minimum: 0, maximum: 100 },
  },
} as const;
